services:
  pytorch:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/pytorch/Dockerfile
      target: development
    volumes:
      - ./ml-dcs:/usr/local/src/ml-dcs
    ports:
      - "8000:8000"
    env_file: ./ml-dcs/.env
    environment:
      PORT: "8000"
      TZ: "Asia/Tokyo"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
