services:
  anaconda:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./ml-dcs:/usr/local/src/ml-dcs
    ports:
      - "8000:8000"
    env_file: ./ml-dcs/.env
    environment:
      PORT: "8000"
      TZ: "Asia/Tokyo"
