[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | _build
  | __pycache__
  | buck-out
  | build
  | dist
  | migrations
  | vendor
  | 243_.*
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = [
    ".git",
    ".tox",
    ".venv",
    "_build",
    "__pycache__",
    "buck-out",
    "build",
    "dist",
    "migrations",
    "vendor",
    "243_*",
]
